"use client";
import "../styles/globals.css";
import Header from "@/components/header";
import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import Popular from "@/components/popular";
import Locations from "@/components/locations";
import Footer from "@/components/footer";
import { Inter } from "next/font/google";
import NavbarLogin from "@/components/navbarlogin";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
      {pathname !== "/potrait" ? (
          pathname !== "/galery" &&
          pathname !== "/request" &&
          pathname !== "/login" &&
          pathname !== "/register" &&
          pathname !== "/" &&
          <NavbarLogin/>
        ) : (
          <></>
        )}
        {pathname !== "/" &&
        pathname !== "/potrait" &&
        pathname !== "/galery" ? (
          pathname !== "/login" && pathname !== "/register" &&
          pathname !== "/sukseslogin" &&
          <Header />
        ) : (
          <></>
        )}
        {pathname !== "/potrait" && pathname !== "/galery" ? (
          pathname !== "/request" && pathname !== "/login" && pathname !== "/register" &&
          pathname !== "/sukseslogin" && <Navbar />
        ) : (
          <></>
        )}
        {children}
        {pathname !== "/potrait" && pathname !== "/galery" ? (
          pathname !== "/request" && pathname !== "/login" && pathname !== "/register" &&
           <Popular />
        ) : (
          <></>
        )}

        {pathname !== "/potrait" ? (
          pathname !== "/galery" &&
          pathname !== "/request" &&
          pathname !== "/login" &&
          pathname !== "/register" &&
          <Locations />
        ) : (
          <></>
        )}

        {pathname !== "/login" &&
        pathname !== "/register"&&
        <Footer />}
      </body>
    </html>
  );
}
